<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <artifactId>ssa-api-parent</artifactId>
    <groupId>com.i2i</groupId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <artifactId>ssa-api-order</artifactId>
  <packaging>jar</packaging>

  <dependencies>
    <dependency>
      <groupId>com.i2i</groupId>
      <artifactId>ssa-api-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.i2i</groupId>
      <artifactId>ssa-model-order</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.i2i</groupId>
      <artifactId>ssa-model-customer</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.i2i</groupId>
      <artifactId>ssa-model-cart</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
    </dependency>
    <dependency>
      <groupId>com.i2i</groupId>
      <artifactId>ssa-client-customer</artifactId>
      <version>${project.version}</version>
    </dependency>

    <dependency>
      <groupId>com.i2i</groupId>
      <artifactId>ssa-client-cart</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>
 <!--
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.2.2</version>
        <configuration>
          <archive>
            <manifest>
              <mainClass>com.i2i.ssa.api.order.OrderRestApplication</mainClass>
              <addClasspath>true</addClasspath>
              <classpathPrefix>lib/</classpathPrefix>
            </manifest>
          </archive>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.6.1</version>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>package</phase>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/lib</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build> -->




  <build>
    <plugins>
      <!-- Spring Boot Maven Plugin -->
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- Maven Resources Plugin -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.2.0</version>
        <executions>
          <execution>
            <id>copy-classes-to-root</id>
            <phase>package</phase>
            <goals>
              <goal>resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/classes</outputDirectory>
              <resources>
                <resource>
                  <directory>${project.build.outputDirectory}</directory>
                  <includes>
                    <include>com/**</include>
                  </includes>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>


</project>
