<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <packaging>pom</packaging>
  <groupId>com.i2i</groupId>
  <artifactId>ssa-parent</artifactId>
  <version>${project.version}</version>
  <name>Self Service Application</name>
  <description>Self Service Application Training Project</description>

  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <java.version>21</java.version>
    <lombok.version>1.18.36</lombok.version>
    <jetbrains.annotations.version>24.0.0</jetbrains.annotations.version>
    <project.version>0.0.1-SNAPSHOT</project.version>
    <spring-cloud.version>2024.0.0</spring-cloud.version>
  </properties>

  <modules>
    <module>ssa-api-parent</module>
    <module>ssa-client-parent</module>
    <module>ssa-gui</module>
    <module>ssa-model-parent</module>
      <module>config-server</module>
      <module>eureka-server</module>
  </modules>

  <dependencies>

    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>${lombok.version}</version>
      <optional>true</optional>
    </dependency>

    <dependency>
      <groupId>org.jetbrains</groupId>
      <artifactId>annotations</artifactId>
      <version>${jetbrains.annotations.version}</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>3.4.1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

</project>
