version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ##image: customer-api-docker:latest # Replace with your actual image name
    container_name: customer-api-container
    ports:
      - "8089:8089" # Map the container's port 8089 to the host's port 8089
    environment:
      - SPRING_PROFILES_ACTIVE=h2 # Activate the 'h2' profile if configured
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=sa